# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.2

- pip:
  - azureml-defaults==1.0.62.*
  - tensorflow==1.13.1
  - keras==2.2.4
  - matplotlib==3.1.1
  - opencv-python==4.1.1.26
  - Pillow
channels:
- conda-forge
